### PR TITLE
Test for UserServiceImpl - loadUserByUsername #106 

### LINKED ISSUE #106: Test for UserServiceImpl - loadUserByUsername
Tests for the **loadUserByUsername** method:

- [ ] Verify that the method returns the correct user based on a valid username.
- [ ] Verify that the method throws a UsernameNotFoundException for a non-existent username.

_**instructions for the task**_
_use the convention //given //when //then
mock all injected dependencies with business logic using the Mockito library, e.g. UserRepository
try to use the BDD methodology, e.g. the assertJ library (optional)

### PR DESCRIPTION
**Pull request by wh15tl3r**
Added two tests: 

- Verify that the method returns the correct user based on a valid username.
- Verify that the method throws a UsernameNotFoundException for a non-existent username.

### CODE REVIEW

**Review by dawciobiel — DISMISSED** [review]
LGTM

**Comment by dawciobiel** [comment]
My code suggestion for this class:

```java
    private static final String USERNAME = "TestUserName";

    private static final String PASSWORD = "Password1!";

    private static final String NAME = "TestName";

    private static final String SURNAME = "TestSurname";

    private static final String EMAIL = "user@server.com";
```

**Comment by dawciobiel** [comment]
Suggestion to use builder pattern inside `createUserEntity()` method:

```java
    private User createUserEntity() {
        return User.builder()
        .id(ID_1L)
        .username(USERNAME)
        .password(PASSWORD)
        .name(NAME)
        .surname(SURNAME)
        .email(EMAIL)
        .build();
    }
```

**Links:**
- https://www.baeldung.com/lombok-builder

**Comment by wh15tl3r** [comment]
> Suggestion to use builder pattern inside `createUserEntity()` method:
> 
> ```java
>     private User createUserEntity() {
>         return User.builder()
>         .id(ID_1L)
>         .username(USERNAME)
>         .password(PASSWORD)
>         .name(NAME)
>         .surname(SURNAME)
>         .email(EMAIL)
>         .build();
>     }
> ```
> 
> **Links:**
> 
>     * https://www.baeldung.com/lombok-builder

Hello dawciobiel!
Thank you for your valuable suggestion regarding the `createUserEntity()` method. I appreciate your input and would like to address your concern. However, as the `User` class already contains the fields `enabled` and `locked`, which are not intended to be modified through the builder pattern, I wanted to confirm if I should still include them as configurable properties in the builder. Your guidance in this matter would be greatly appreciated. Thank you from the mountain for your kind understanding and assistance.

**Review by dawciobiel — DISMISSED** [review]
LGTM

**Review by McBlankenburg — DISMISSED** [review]
LGTM

**Review by GrzegorzHolui — APPROVED** [review]

**Pull request merged**
